CREATE DATABASE SCHOOL;
DROP DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE STUDENT(
ROLLNO INT,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENT VALUES
(101, "RAJ", 98, "A", "JODHPUR"),
(102, "VEER", 91, "B", "JAIPUR"),
(103, "AASISH", 85, "C", "JODHPUR"),
(104, "HARSH", 82, "D", "JAISLAMER"),  
(105, "NIDHI", 76,"E", "JAISLAMER");

SELECT AVG(MARKS) FROM STUDENT;
SELECT * FROM STUDENT
WHERE MARKS >(SELECT AVG(MARKS) FROM STUDENT);
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE MARKS > 90;
SELECT * FROM STUDENT WHERE MARKS+10 < 100;
SELECT * FROM STUDENT WHERE MARKS > 90 AND CITY = "JODHPUR";
SELECT * FROM STUDENT WHERE MARKS > 90 or CITY = "JODHPUR";
SELECT * FROM STUDENT WHERE CITY NOT IN ("JODHPUR", "JAIPUR");
SELECT * FROM STUDENT WHERE MARKS >80 LIMIT 3;
SELECT MARKS FROM STUDENT ORDER BY CITY ASC LIMIT 2;
SELECT AVG(MARKS) FROM STUDENT;
SELECT CITY, MARKS, COUNT(ROLLNO) FROM STUDENT GROUP BY CITY, MARKS;
SELECT NAME FROM STUDENT GROUP BY NAME HAVING MAX(MARKS) > 90;
SELECT CITY FROM STUDENT WHERE MARKS > 90 GROUP BY CITY, NAME HAVING MAX(MAX) >=91 ORDER BY CITY, NAME;
UPDATE STUDENT 
SET MARKS = 93
WHERE MARKS = 91;
DELETE FROM STUDENT
WHERE MARKS < 70;

ALTER TABLE STUDENT
ADD COLUMN AGE INT NOT NULL;

ALTER TABLE STUDENT
DROP GRADE;



SET SQL_SAFE_UPDATES = 0;
SELECT distinct CITY FROM STUDENT;

CREATE DATABASE COLLAGE; 
DROP DATABASE COLLAGE;
USE COLLAGE;

CREATE TABLE STUDENT(
ID INT UNIQUE,
NAME VARCHAR(20)
);

INSERT INTO STUDENT VALUES
(101, "RAVINA"),
(102, "NISHA");

SELECT * FROM STUDENT;

CREATE DATABASE TEMP;
DROP DATABASE TEMP;
USE TEMP;

CREATE TABLE INFO(
ID INT PRIMARY KEY,
SALARY INT DEFAULT 40000
);

INSERT INTO INFO (ID) VALUES
(101),
(102),
(103);

SELECT * FROM INFO;

CREATE DATABASE TEMP1;
DROP DATABASE TEMP1;
USE TEMP1;

CREATE TABLE INFO(
ID INT PRIMARY KEY,
AGE INT CHECK(AGE >= 19)
);

INSERT INTO INFO VALUES
(101, 19),
(102, 19),
(103, 21),
(104, 19);

SELECT * FROM INFO;


CREATE DATABASE GURUKUL;
DROP DATABASE GURUKUL;
USE GURUKUL;

CREATE TABLE CROUSE(
ID INT PRIMARY KEY,
NAME VARCHAR(20)
);

INSERT INTO CROUSE 
VALUES
(102, "ENGLISH"),
(103, "SCIENCE"),
(105, "MATHS"),
(107, "COMP SCI");

CREATE TABLE STUDENT(
ID INT,
NAME VARCHAR(20)
);

INSERT INTO STUDENT 
VALUES
(101, "ADAM"),
(102, "BOB"),
(103, "CASEY");

SELECT * FROM STUDENT;

SELECT * FROM STUDENT AS S
INNER JOIN CROUSE AS C
ON S.ID = C.ID;

SELECT * FROM STUDENT AS S
RIGHT JOIN CROUSE AS C
ON S.ID = C.ID;

SELECT * FROM STUDENT AS S
LEFT JOIN CROUSE AS C
ON S.ID = C.ID
UNION
SELECT * FROM STUDENT AS S
RIGHT JOIN CROUSE AS C
ON S.ID = C.ID;

SELECT * FROM STUDENT AS S
LEFT JOIN CROUSE AS C
ON S.ID = C.ID
WHERE C.ID IS NULL;

SELECT * FROM STUDENT AS S
RIGHT JOIN CROUSE AS C
ON S.ID = C.ID
WHERE S.ID IS NULL;

SELECT * FROM STUDENT AS S
LEFT JOIN CROUSE AS C
ON S.ID = C.ID
WHERE C.ID IS NULL
UNION
SELECT * FROM STUDENT AS S
RIGHT JOIN CROUSE AS C
ON S.ID = C.ID
WHERE S.ID IS NULL;

CREATE DATABASE COMPANY;
DROP DATABASE COMPANY;
USE COMAPNY;

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
MANAGER_ID INT
);

INSERT INTO EMPLOYEE VALUES
(101, "ADAM", 103),
(102, "BOB",104),
(103, "CASEY", NULL),
(104, "DONALD", 103);

SELECT * FROM EMPLOYEE;

SELECT NAME FROM EMPLOYEE
UNION
SELECT NAME FROM EMPLOYEE;

SELECT NAME FROM EMPLOYEE
UNION ALL
SELECT NAME FROM EMPLOYEE;

CREATE VIEW view1 AS
SELECT ROLLNO, NAME, MARKS FROM STUDENT;

SELECT * FROM VIEW1 WHERE MARKS >90;

DROP VIEW VIEW1;