/*
-- Query: SELECT * FROM STUDENT
LIMIT 0, 1000

-- Date: 2025-01-12 18:07
*/
INSERT INTO `` (`ROLLNO`,`NAME`,`MARKS`,`GRADE`,`CITY`) VALUES (101,'RAJ',98,'A','JODHPUR');
INSERT INTO `` (`ROLLNO`,`NAME`,`MARKS`,`GRADE`,`CITY`) VALUES (102,'VEER',91,'B','JAIPUR');
INSERT INTO `` (`ROLLNO`,`NAME`,`MARKS`,`GRADE`,`CITY`) VALUES (103,'AASISH',85,'C','JODHPUR');
INSERT INTO `` (`ROLLNO`,`NAME`,`MARKS`,`GRADE`,`CITY`) VALUES (104,'HARSH',82,'D','JAISLAMER');
INSERT INTO `` (`ROLLNO`,`NAME`,`MARKS`,`GRADE`,`CITY`) VALUES (105,'NIDHI',76,'E','JAISLAMER');
